### PR TITLE
Fixes #31 Intermittent failures io.vertx.ext.dropwizard.MetricsTest.testHttpMetricsOnClose

### LINKED ISSUE #31: Intermittent failures io.vertx.ext.dropwizard.MetricsTest.testHttpMetricsOnClose
```
java.lang.IllegalStateException: Timed out
	at io.vertx.test.core.AsyncTestBase.waitUntil(AsyncTestBase.java:611)
	at io.vertx.test.core.AsyncTestBase.waitUntil(AsyncTestBase.java:596)
	at io.vertx.ext.dropwizard.MetricsTest.testHttpMetricsOnClose(MetricsTest.java:363)
```

### PR DESCRIPTION
**Pull request by tsegismont**
If the snapshot is taken before the SPI callbacks are called, it will not be empty and will never be.

Call #testComplete after the SPI callbacks are invoked. The snapshot should then be correct on the first check.

### CODE REVIEW

File: src/test/java/io/vertx/ext/dropwizard/MetricsTest.java [hunk 1]
```diff
@@ -353,14 +347,14 @@ public void testHttpMetricsOnClose() throws Exception {
     client.close();
     server.close(ar -> {
       assertTrue(ar.succeeded());
-      testComplete();
+      vertx.setTimer(100, tid -> testComplete());
```
Comment (pmlopes) [inline src/test/java/io/vertx/ext/dropwizard/MetricsTest.java]: maybe instead of adding a delay, doing just:

```java
vertx.runOnContext(v -> testComplete());
```

Is faster and does the same. the `runOnContext` can also be seen as node.js `process.nextTick` a simple way to execute something on the next event loop cycle, this allows the pending operations to terminate.

Comment (tsegismont) [inline src/test/java/io/vertx/ext/dropwizard/MetricsTest.java]: Thanks Paulo. The code is updated, we just talked about this with Julien on
IRC.

2016-06-09 16:17 GMT+02:00 Paulo Lopes <notifications@github.com>:
