### PR TITLE
Fixes #56 Intermittent failure in MetricsTest#testHttpMetricsOnClose

### LINKED ISSUE #56: Intermittent failure in MetricsTest#testHttpMetricsOnClose
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.vertx.test.core.AsyncTestBase.assertTrue(AsyncTestBase.java:372)
	at io.vertx.ext.dropwizard.MetricsTest.testHttpMetricsOnClose(MetricsTest.java:364)
```

### PR DESCRIPTION
**Pull request by tsegismont**
Allow http server metrics to be completely removed from the registry

### CODE REVIEW

File: src/test/java/io/vertx/ext/dropwizard/MetricsTest.java [hunk 1]
```diff
@@ -354,14 +354,15 @@ public void testHttpMetricsOnClose() throws Exception {
     client.close();
     server.close(ar -> {
       assertTrue(ar.succeeded());
-      vertx.runOnContext(v -> testComplete());
+      // This allows http server metrics to be completely removed from the registry
+      vertx.setTimer(100, v -> testComplete());
```
Comment (vietj) [inline src/test/java/io/vertx/ext/dropwizard/MetricsTest.java]: this should rather loop until `metricsService.getMetricsSnapshot(server).getMap().isEmpty()` and a timer < 10000 millis:

```
AtomicInteger count = new AtomicInteger(100);
vertx.setPeriodic(100, id -> {
  if (count.decrementAndGet() == 0) {
     vertx.cancelPeriodic(id);
     fail();
  } else if (metricsService.getMetricsSnapshot(server).getMap().isEmpty()) {
     vertx.cancelPeriodic(id);
     testComplete();
  }
});
```

**Comment by tsegismont** [comment]
Update the PR, not exactly as suggested, but with simple loop/sleep code in
the main test thread

2016-12-23 10:41 GMT+01:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
LGTM
